#services:
#  webapp:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile
#    volumes:
#      - './:/var/www/html'
#      - './deploy/docker/webapp/php.ini:/usr/local/etc/php/conf.d/php.ini'
#      - './deploy/docker/webapp/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini'
#    stdin_open: true
#    tty: true
#    expose:
#      - '9000'
#    container_name: webapp
#    depends_on:
#      - database
#
#  nginx:
#    image: 'nginx:latest'
#    restart: always
#    ports:
#      - '80:80'
#    volumes:
#      - './deploy/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf' # TODO:
#      - './public:/var/www/html/public'
#      - './storage:/var/www/html/storage'
#    depends_on:
#      - webapp
#    container_name: nginx
#
#  database:
#    image: mysql
#    restart: always
#    volumes:
#      - './docker/database/mysql/data:/var/lib/mysql'
#    ports:
#      - '3306:3306'
#    environment:
#      - MYSQL_ROOT_PASSWORD=admin
#      - MYSQL_DATABASE=colibriplus
#    container_name: db
#  node:
#    image: 'node:latest'
#    working_dir: /var/www/html
#    volumes:
#      - './:/var/www/html'
#    container_name: node
#    command: 'sh -c "npm install && npm run build"'
#    ports:
#      - '5173:5173'
#    depends_on:
#      - webapp
#
#volumes:
#  sail-mysql:
#    driver: local
#
#networks:
#  sail:
#    driver: bridge
