services:
  app:
    container_name: masteringx-app
    image: my/laravel-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "80:8080"   # maps host port 80 → container's port 8080 (HTTP)
      - "443:8443"  # maps host port 443 → container's port 8443 (HTTPS)
    environment:
      SSL_MODE: "full"
      PHP_OPCACHE_ENABLE: 1
      AUTORUN_ENABLED: "true"
    restart: unless-stopped
    volumes:
      - storage:/var/www/html/storage
    depends_on:
      - mysql
    networks:
      - production


  mysql:
    image: mysql:8.0
    restart: unless-stopped
    container_name: mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - production
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
      retries: 10
      interval: 20s
      timeout: 5s
      start_period: 30s
  redis:
    image: redis:6
    command: "redis-server --appendonly yes --requirepass redispassword"

  horizon:
    image: my/laravel-app
    command: [ "php", "/var/www/html/artisan", "horizon" ]
    stop_signal: SIGTERM # Set this for graceful shutdown if you're using fpm-apache or fpm-nginx
    healthcheck:
      test: [ "CMD", "healthcheck-horizon" ]
      start_period: 10s

volumes:
  storage:
  mysql-data:

networks:
  production:
